apiVersion: apps/v1
kind: Deployment
metadata:
  name: com-23people-app
  labels:
    app: 23people
spec:
  selector:
    matchLabels:
      app: 23people
  template:
    metadata:
      labels:
        app: 23people
    spec:
      containers:
        - name: com-23people-app
          image: gcr.io/com-23people-app/com-23people-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: spring.datasource.username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: spring.datasource.password
#        - name: cloudsql-proxy
#          image: gcr.io/cloudsql-docker/gce-proxy:1.16
#          command: ["/cloud_sql_proxy",
#                    "-instances=com-23people-app:southamerica-east1:mysql23people=tcp:3306",
#                    "-credential_file=/secrets/cloudsql/credentials.json"]
#          securityContext:
#            runAsUser: 2
#            allowPrivilegeEscalation: false
#          volumeMounts:
#            - name: cloudsql-instance-credentials
#              mountPath: /secrets/cloudsql
#              readOnly: true
#      volumes:
#        - name: cloudsql-instance-credentials
#          secret:
#            secretName: cloudsql-instance-credentials
        
      